export default {
  moduleFileExtensions: ['js', 'json', 'ts'],
  testRegex: String.raw`.*\.spec\.ts$`,
  transform: {
    [String.raw`^.+\.(t|j)s$`]: 'ts-jest',
  },
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
  },
  collectCoverage: true,
  coverageReporters: ['text-summary', 'text', 'lcov', 'cobertura'],
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!**/*.spec.(t|j)s',
    '!**/*.module.(t|j)s',
    '!**/main.(t|j)s',
    '!**/*.d.ts',
    '!**/*.dto.(t|j)s',
    '!**/*.entity.(t|j)s',
    '!**/*.entities.(t|j)s',
    '!**/*.interface.(t|j)s',
    '!**/*.interfaces.(t|j)s',
    '!**/*.enum.(t|j)s',
    '!**/*.constant.(t|j)s',
    '!**/*.constants.(t|j)s',
    '!**/database/migrations/**',
    '!**/index.ts',
    '!**/reports/**',
  ],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/reports/',
    '/config/environments/',
    '/database/migrations/',
    '/src/main.ts',
  ],
  testEnvironment: 'node',
  coverageThreshold: {
    global: {
      statements: 0,
      branches: 0,
      functions: 0,
      lines: 0,
    },
    './src/**/*.service.ts': {
      statements: 0,
      branches: 0,
      functions: 0,
      lines: 0,
    },
    './src/shared/utilities/**/*.ts': {
      statements: 0,
      branches: 0,
      functions: 0,
      lines: 0,
    },
  },
  coverageDirectory: '<rootDir>/reports/coverage',
};
