sonar.projectKey=sto-info-app_sto-info-file-scan-worker
sonar.organization=sto-info-app

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=STO Info File Scan Worker
sonar.projectVersion=${env.PROJECT_VERSION}

# Core settings
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/reports/**
sonar.javascript.lcov.reportPaths=reports/coverage/lcov.info

# Never require coverage for these
sonar.coverage.exclusions=\
src/main.ts,\
src/app.module.ts,\
src/**/*.module.ts,\
src/**/*.constants.ts,\
src/**/*.dto.ts,\
src/**/*.entity.ts,\
src/**/*.entities.ts,\
src/main.ts,\
src/database/migrations/**,\
src/**/index.ts

# Exclude database migrations from duplicate code detection
sonar.cpd.exclusions=src/database/migrations/**

# Ignore certain rules in test/spec files only
sonar.issue.ignore.multicriteria=e1,e2

# S1313: "Using hardcoded IP addresses is security-sensitive"
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S1313
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.spec.ts,**/__tests__/**,**/test/**,**/tests/**

# S6684: "Hard-coded passwords are security-sensitive"
sonar.issue.ignore.multicriteria.e2.ruleKey=secrets:S6684
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.spec.ts,**/__tests__/**,**/test/**,**/tests/**
